[package]
name = "enchanted_natures"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
actix-web = "4.3.1"
paperclip = { version = "0.7.0"}
actix-rt = "2.5.0"
dotenv = "0.15"
tokio = { version = "1", features = ["full"] }
uuid = { version = "0.8", features = ["v4", "serde"] }

actix-cors = "0.6.0-beta.1"
actix-files = "0.6.0-beta.8"
actix-identity = "0.4.0"
env_logger = "0.9.0"
serde = { version = "1.0.152", features = ["derive"]}
serde_json = "1.0.93"
config = "0.11"
chrono = { version = "0.4.15", features = ["serde"]} 
log = "0.4"
tracing = { version = "0.1", features = ["log" ] }

[dependencies.sqlx]
version = "0.5.7"
features = [ "postgres", "runtime-actix-rustls", "macros", "uuid", "chrono", "migrate" ]

[dev-dependencies]
reqwest = {version = "0.11", features = ["json"] }
