### name=Get Categories
### summary=Get a list of categories
GET {{url}}/api/v0/categories

### name=Create Category
### summary=Create Flora category
PUT {{url}}/api/v0/categories
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

{
    "name": "Flora",
    "description": "Flora"
}

### name=Create Fauna Category
PUT {{url}}/api/v0/categories
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

{
    "name": "Fauna",
    "description": "Fauna"
}

### name=Create Landscape Category
PUT {{url}}/api/v0/categories
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

{
  "name": "Landscape",
  "description": "Landscape"
}

### name=Get Categories
GET {{url}}/api/v0/categories
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

>> categories.json

