### name=Get Categories
### summary=Get a list of categories
GET {{url}}/api/v0/categories

### name=Create Category
### summary=Create Flora category
PUT {{url}}/api/v0/categories
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

{
    "name": "Flora",
    "description": "Flora"
}

### name=Create Fauna Category
PUT {{url}}/api/v0/categories
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

{
    "name": "Fauna",
    "description": "Fauna"
}

### name=Create Landscape Category
PUT {{url}}/api/v0/categories
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

{
  "name": "Landscape",
  "description": "Landscape"
}

### name=Get Category
GET {{url}}/api/v0/categories/1
Accept-Encoding: gzip, deflate, br
Content-Type: application/json


### name=Delete Category
DELETE {{url}}/api/v0/categories
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

{
  "id": 1
}

###
# @name Add Photo To Category
POST {{url}}/api/v0/categories/1
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

{
  "photoId" : 1,
  "displayOrder": 1
}