###
### @name add photo to category
PUT {{url}}/api/v0/photos/3
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

{
    "title":"79",
    "description":"BMW",
    "filename":"79.jpg"
}

>> updated.json
