### name=Create Landscape Category
POST {{url}}/api/v0/categories
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

{
  "name": "mode de vie",
  "description": "mode de vie"
}

> {%
    client.global.set("category_id", response.body.id);
%}

### @name Add 79 Photos
POST {{url}}/api/v0/photos
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

{
    "title": "79",
    "filename": "79.jpg",
    "description": "BMW",
    "location_taken": "ashburn, va",
    "date_taken": "2022-12-16T16:40:36Z"
}

> {%
    client.global.set("photo_id", response.body.id);
%}

>> photos.json

###
### @name add photo to category
POST {{url}}/api/v0/categories/{{category_id}}/photos
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

{
    "photo_id": {{photo_id}},
    "display_order": 0
}

>> cate.json
