###
### @name Create portfolio category
POST {{url}}/api/v0/categories
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

{
    "name": "portfolio",
    "description": "portfolio"
}

###
### @name Create diptych category
POST {{url}}/api/v0/categories
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

{
    "name": "diptych",
    "description": "diptych"
}

###
### @name Create fauna category
POST {{url}}/api/v0/categories
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

{
    "name": "fauna",
    "description": "fauna"
}

###
### @name Create flora category
POST {{url}}/api/v0/categories
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

{
    "name": "flora",
    "description": "flora"
}

###
### @name Create landscape category
POST {{url}}/api/v0/categories
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

{
    "name": "landscape",
    "description": "landscape"
}

###
### @name Create live! category
POST {{url}}/api/v0/categories
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

{
    "name": "live!",
    "description": "live!"
}

###
### @name Create mode de vie category
POST {{url}}/api/v0/categories
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

{
    "name": "mode de vie",
    "description": "mode de vie"
}

###
### @name Create oiseaux category
POST {{url}}/api/v0/categories
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

{
    "name": "oiseaux",
    "description": "oiseaux"
}

### 
### @name Get Categories
GET {{url}}/api/v0/categories
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

>>! all_categories.json
