### name=Create Landscape Category
POST {{url}}/api/v0/photos
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

{
  "name": "Landscape",
  "description": "Landscape",
  "url": "test"
}

###
GET {{url}}/api/v0/photos
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

###
#@name Get Photo By Id
< {%
    request.variables.set("id", "3")
%}
GET {{url}}/api/v0/photos/{{id}}
Accept-Encoding: gzip, deflate, br
Content-Type: application/json
